name: WhatsApp PBL Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp Message
        run: |
          # Ganti NOMOR_HP dengan nomor kamu (contoh: 62812345678)
          # Ganti API_KEY_KAMU dengan kode yang nanti dikirim bot
          curl -X GET "https://api.callmebot.com/whatsapp.php?phone=NOMOR_HP&text=🚀+*UPDATE+CODINGAN+PBL*%0A%0A👤+Oleh:+${{ github.actor }}%0A📝+Pesan:+${{ github.event.head_commit.message }}%0A🔗+Link:+${{ github.event.head_commit.url }}&apikey=API_KEY_KAMU"